//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HistoriaClinica.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerPacientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarPacienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::HistoriaClinica.Properties.Settings.Default.HistoriaClinica_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerPacientesCompletedEventHandler obtenerPacientesCompleted;
        
        /// <remarks/>
        public event obtenerPacienteCompletedEventHandler obtenerPacienteCompleted;
        
        /// <remarks/>
        public event guardarPacienteCompletedEventHandler guardarPacienteCompleted;
        
        /// <remarks/>
        public event actualizarPacienteCompletedEventHandler actualizarPacienteCompleted;
        
        /// <remarks/>
        public event eliminarPacienteCompletedEventHandler eliminarPacienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerPacientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable obtenerPacientes() {
            object[] results = this.Invoke("obtenerPacientes", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPacientesAsync() {
            this.obtenerPacientesAsync(null);
        }
        
        /// <remarks/>
        public void obtenerPacientesAsync(object userState) {
            if ((this.obtenerPacientesOperationCompleted == null)) {
                this.obtenerPacientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPacientesOperationCompleted);
            }
            this.InvokeAsync("obtenerPacientes", new object[0], this.obtenerPacientesOperationCompleted, userState);
        }
        
        private void OnobtenerPacientesOperationCompleted(object arg) {
            if ((this.obtenerPacientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPacientesCompleted(this, new obtenerPacientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable obtenerPaciente(int id) {
            object[] results = this.Invoke("obtenerPaciente", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPacienteAsync(int id) {
            this.obtenerPacienteAsync(id, null);
        }
        
        /// <remarks/>
        public void obtenerPacienteAsync(int id, object userState) {
            if ((this.obtenerPacienteOperationCompleted == null)) {
                this.obtenerPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPacienteOperationCompleted);
            }
            this.InvokeAsync("obtenerPaciente", new object[] {
                        id}, this.obtenerPacienteOperationCompleted, userState);
        }
        
        private void OnobtenerPacienteOperationCompleted(object arg) {
            if ((this.obtenerPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPacienteCompleted(this, new obtenerPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable guardarPaciente(Paciente Datos) {
            object[] results = this.Invoke("guardarPaciente", new object[] {
                        Datos});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void guardarPacienteAsync(Paciente Datos) {
            this.guardarPacienteAsync(Datos, null);
        }
        
        /// <remarks/>
        public void guardarPacienteAsync(Paciente Datos, object userState) {
            if ((this.guardarPacienteOperationCompleted == null)) {
                this.guardarPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarPacienteOperationCompleted);
            }
            this.InvokeAsync("guardarPaciente", new object[] {
                        Datos}, this.guardarPacienteOperationCompleted, userState);
        }
        
        private void OnguardarPacienteOperationCompleted(object arg) {
            if ((this.guardarPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarPacienteCompleted(this, new guardarPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable actualizarPaciente(int id, Paciente Datos) {
            object[] results = this.Invoke("actualizarPaciente", new object[] {
                        id,
                        Datos});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarPacienteAsync(int id, Paciente Datos) {
            this.actualizarPacienteAsync(id, Datos, null);
        }
        
        /// <remarks/>
        public void actualizarPacienteAsync(int id, Paciente Datos, object userState) {
            if ((this.actualizarPacienteOperationCompleted == null)) {
                this.actualizarPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarPacienteOperationCompleted);
            }
            this.InvokeAsync("actualizarPaciente", new object[] {
                        id,
                        Datos}, this.actualizarPacienteOperationCompleted, userState);
        }
        
        private void OnactualizarPacienteOperationCompleted(object arg) {
            if ((this.actualizarPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarPacienteCompleted(this, new actualizarPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable eliminarPaciente(int id) {
            object[] results = this.Invoke("eliminarPaciente", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarPacienteAsync(int id) {
            this.eliminarPacienteAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarPacienteAsync(int id, object userState) {
            if ((this.eliminarPacienteOperationCompleted == null)) {
                this.eliminarPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarPacienteOperationCompleted);
            }
            this.InvokeAsync("eliminarPaciente", new object[] {
                        id}, this.eliminarPacienteOperationCompleted, userState);
        }
        
        private void OneliminarPacienteOperationCompleted(object arg) {
            if ((this.eliminarPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarPacienteCompleted(this, new eliminarPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente {
        
        private int idField;
        
        private string primer_nombreField;
        
        private string segundo_nombreField;
        
        private string primer_apellidoField;
        
        private string segundo_apellidoField;
        
        private string tipo_identificacionField;
        
        private string identificacionField;
        
        private string telefonoField;
        
        private string direccionField;
        
        private int edadField;
        
        private string sexoField;
        
        private string fecha_nacimientoField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                this.primer_nombreField = value;
            }
        }
        
        /// <remarks/>
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                this.segundo_nombreField = value;
            }
        }
        
        /// <remarks/>
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                this.primer_apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                this.segundo_apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_identificacion {
            get {
                return this.tipo_identificacionField;
            }
            set {
                this.tipo_identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
            }
        }
        
        /// <remarks/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                this.fecha_nacimientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void obtenerPacientesCompletedEventHandler(object sender, obtenerPacientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPacientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPacientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void obtenerPacienteCompletedEventHandler(object sender, obtenerPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void guardarPacienteCompletedEventHandler(object sender, guardarPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void actualizarPacienteCompletedEventHandler(object sender, actualizarPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarPacienteCompletedEventHandler(object sender, eliminarPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591